name: workflow
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: git config user.email "workflow@github.actions" && git config user.name "GH Actions Ticker" && git checkout master && git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/seankhliao/arch-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBPAT }}
      - run: curl -s https://proxy.golang.org/golang.zx2c4.com/wireguard/@v/list | head -n 1 > VERSION
      - run: git diff-index --quiet HEAD && git add VERSION && git commit -m $(cat VERSION) && git tag $(cat VERSION) && git push origin $(cat VERSION) || return true
